doc: refine the transaction example in the README (#2072)
I tried the command in the readme and met the following errors during my
work
```sh
thread 'main' panicked at bin/fuel-core-client/src/main.rs:52:50:
invalid transaction json: Error("missing field `script`", line: 1, column: 133)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I replaced it with the `tx` from the test file below by using the
function `to_json()`

https://github.com/FuelLabs/fuel-core/blob/a9e5e89f5fb38e3b3d6e6bdfe1ad339a01f2f3b9/tests/tests/tx.rs#L155-L172